// Builds standalone `mc-mod` executables (Bun runtime + CLI + web UI in one file) with `bun build --compile`.
// Run `bun run build` first: the web UI is read from apps/cli/dist/web.
//
//   bun run compile                        this machine's platform only
//   bun run compile --all                  every release target
//   bun run compile --target linux-x64     one target (repeatable)
//
// Binaries land in dist/release/ (not apps/cli/dist, which is published to npm), with SHA256SUMS.

import { mkdir, rm } from 'node:fs/promises'
import path from 'node:path'
import { parseArgs } from 'node:util'
import { z } from 'zod'

/** Release targets → Bun compile targets. x64 uses the baseline build so older CPUs (no AVX2) work. */
const TARGETS = {
  'linux-x64': 'bun-linux-x64-baseline',
  'linux-arm64': 'bun-linux-arm64',
  'darwin-x64': 'bun-darwin-x64-baseline',
  'darwin-arm64': 'bun-darwin-arm64',
  'windows-x64': 'bun-windows-x64-baseline',
} as const
type Target = keyof typeof TARGETS
const TargetName = z.enum(Object.keys(TARGETS) as [Target, ...Target[]])

const root = path.resolve(import.meta.dir, '..')
const cliDir = path.join(root, 'apps/cli')
const webDir = path.join(cliDir, 'dist/web')
const entryDir = path.join(cliDir, '.compile')
const outDir = path.join(root, 'dist/release')

const { values } = parseArgs({
  options: { all: { type: 'boolean', default: false }, target: { type: 'string', multiple: true } },
})
const targets: Target[] = values.all
  ? TargetName.options
  : values.target?.length
    ? values.target.map((t) => TargetName.parse(t))
    : [hostTarget()]

function hostTarget(): Target {
  const os = { linux: 'linux', darwin: 'darwin', win32: 'windows' }[process.platform as string]
  return TargetName.parse(`${os}-${process.arch}`)
}

if (!(await Bun.file(path.join(webDir, 'index.html')).exists())) {
  throw new Error(
    `Web UI not found at ${path.relative(root, webDir)}. Run \`bun run build\` first.`,
  )
}

// The entry imports every web file with `type: 'file'`, which embeds it in the executable and gives
// its path inside the binary. `run()` serves them by URL path.
const files = [...new Bun.Glob('**/*').scanSync({ cwd: webDir })]
  .map((f) => f.split(path.sep).join('/'))
  .sort()
const imports = files.map((f, i) => `import f${i} from '../dist/web/${f}' with { type: 'file' }`)
const entries = files.map((f, i) => `  ${JSON.stringify(`/${f}`)}: f${i},`)
await rm(entryDir, { recursive: true, force: true })
await mkdir(entryDir, { recursive: true })
const entry = path.join(entryDir, 'entry.ts')
await Bun.write(
  entry,
  [
    '// Generated by scripts/compile.ts. Do not edit.',
    "import { run } from '../src/cli/run'",
    ...imports,
    '',
    `await run(process.argv, {\n  embeddedWeb: {\n${entries.join('\n')}\n  },\n})`,
    '',
  ].join('\n'),
)

await rm(outDir, { recursive: true, force: true })
await mkdir(outDir, { recursive: true })
const sums: string[] = []
for (const target of targets) {
  const outfile = path.join(outDir, `mc-mod-${target}${target.startsWith('windows') ? '.exe' : ''}`)
  const result = await Bun.build({
    entrypoints: [entry],
    compile: {
      target: TARGETS[target],
      outfile,
      // Like the npm bin's `bun --no-env-file`: never load .env or bunfig.toml from the user's directory.
      autoloadDotenv: false,
      autoloadBunfig: false,
    },
    // Same as the npm bundle: production mode compiles dev mode out (see env.ts IS_BUNDLE).
    define: { 'process.env.NODE_ENV': '"production"' },
    minify: true,
  })
  if (!result.success) {
    for (const log of result.logs) console.error(log)
    throw new Error(`Compile failed for ${target}`)
  }
  const bytes = await Bun.file(outfile).bytes()
  const sha = new Bun.CryptoHasher('sha256').update(bytes).digest('hex')
  sums.push(`${sha}  ${path.basename(outfile)}`)
  console.log(`${path.relative(root, outfile)}  ${(bytes.length / 1024 / 1024).toFixed(1)} MB`)
}
await Bun.write(path.join(outDir, 'SHA256SUMS'), `${sums.join('\n')}\n`)
await rm(entryDir, { recursive: true, force: true })
